### ISSUE TITLE
Would love to contribute

### ISSUE THREAD

**Issue by harsi-dhaliwal** [amanbairagi30/merged-n-share#4]
are you accepting contributions ?
any features i can help build ?

**Comment by amanbairagi30** [comment]
Hi @harsimran-d 
It would be highly appreciated if you would contribute to this repository, 
You are cordially invited to contribute in this merged and share repo .

Currently, in the latest PR . I have added a few features , just give me 1-2 days , I would merge them with master branch and after then I will ping you again with the new features to contribute.

Does that sound okay to you ?

**Comment by amanbairagi30** [comment]
Hi @harsimran-d , Thanks for your patience 
I have recently merged the pr and updated the master branch , now you can jump in for contributing

Also , I would like to request you to revisit the website , i have given cool and fresh look to the website and some features has been added as well.
