### ISSUE TITLE
Make the Y axis numbers strict to integer only 

### ISSUE THREAD

**Issue by amanbairagi30** [amanbairagi30/merged-n-share#5]
At Dashboard , there is a profile views chart where we are showing the user profile views of their public profile page 

But on the chart , there are some non - integers like decimals that can also be seen , that doesn't make sense as the user can be interger only 

Image for reference ![IMG_20241019_114922.jpg](https://github.com/user-attachments/assets/d37dd476-171a-4460-980c-8589ce2186bc)

**Comment by amanbairagi30** [comment]
Hi @harsimran-d

Would you love to start from here ?

**Comment by harsi-dhaliwal** [comment]
on it

**Comment by harsi-dhaliwal** [comment]
i have added the fix to the same Linting and formatting PR #7 

This fix was simple 
just setting the flag `allowDecimals={false}` on the `<YAxis>` component

**Comment by amanbairagi30** [comment]
Okay . Thanks , will review and merge it soon
