### ISSUE TITLE
Proposal: Ensure consistent formatting across all contributors, regardless of their editor.

### ISSUE THREAD

**Issue by harsi-dhaliwal** [amanbairagi30/merged-n-share#6]
Issue Summary

To ensure consistency in code formatting and development workflow across different editors and IDEs, I propose adding the following configuration files to the project:

	•	.editorconfig: To maintain consistent indentation, line endings, and other editor settings.
	•	.eslintrc: To enforce JavaScript/TypeScript code linting standards.
	•	.prettierrc: To ensure consistent code formatting.

This will help minimize unnecessary diffs caused by different formatting styles and improve code readability for everyone.

**Comment by amanbairagi30** [comment]
Go for it @harsimran-d
